name: Test Proxy & SCAN_URL

on:
  workflow_dispatch:  # запуск вручную кнопкой

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install curl_cffi requests beautifulsoup4 lxml

      - name: Run test
        env:
          PROXY_URL: ${{ secrets.PROXY_URL }}
          CHANGE_IP_URL: ${{ secrets.CHANGE_IP_URL }}
          SCAN_URL: ${{ secrets.SCAN_URL }}
        run: test_scan_url.py
